# Baby Steps -Algebra
## Adding two Scalars
To get us started with Theano and get a feel of what we’re working with, let’s make a simple function: add two numbers together. Here is how you do it:



In [3]:
import numpy
import theano.tensor as T
from theano import function

In [4]:
x=T.dscalar('x')
y=T.dscalar('y')
z=x+y
f=function([x,y],z)

In [7]:
f(2,4)

array(6.0)

In [8]:
numpy.allclose(f(16.3,12.1),28.4)

True

## Adding two Matrices


In [9]:
x=T.dmatrix('x')
y=T.dmatrix('y')
z=x+y
f=function([x,y],z)

In [10]:
f([[1,2],[3,4]],[[1,2],[3,4]])

array([[ 2.,  4.],
       [ 6.,  8.]])

The following types are available:

byte: bscalar, bvector, bmatrix, brow, bcol, btensor3, btensor4

16-bit integers: wscalar, wvector, wmatrix, wrow, wcol, wtensor3, wtensor4

32-bit integers: iscalar, ivector, imatrix, irow, icol, itensor3, itensor4

64-bit integers: lscalar, lvector, lmatrix, lrow, lcol, ltensor3, ltensor4

float: fscalar, fvector, fmatrix, frow, fcol, ftensor3, ftensor4

double: dscalar, dvector, dmatrix, drow, dcol, dtensor3, dtensor4

complex: cscalar, cvector, cmatrix, crow, ccol, ctensor3, ctensor4

In [19]:
#Excercise Problem

#Elementwise squaring

a=T.vector()#declaring variable
b=T.vector()
out=a**2+b**2+2*a*b
f=theano.function([a,b],out)
print(f([1,2,1],[1,2,3]))

[  4.  16.  16.]


## Logistic Function

In [20]:
x=T.dmatrix('x')
s=1/(1+T.exp(-x))
logistic=function([x],s)

In [22]:
logistic([[0,1],[2,3]])

array([[ 0.5       ,  0.73105858],
       [ 0.88079708,  0.95257413]])

In [23]:
#Altnative form to compute log
s2=(1+T.tanh(x/2))/2
logistic2=function([x],s2)

In [24]:
logistic([[0,1],[2,3]])

array([[ 0.5       ,  0.73105858],
       [ 0.88079708,  0.95257413]])

## Computing More than one Thing at the Same Time
Theano supports functions with multiple outputs. For example, we can compute the elementwise difference, absolute difference, and squared difference between two matrices a and b at the same time:

In [25]:
a,b=T.dmatrices('a','b')
diff=a-b
abs_diff=abs(diff)
diff_squared=diff**2
f=function([a,b],[diff,abs_diff,diff_squared])

In [27]:
f([[1,2],[3,4]],[[5,6],[7,8]])

[array([[-4., -4.],
        [-4., -4.]]), array([[ 4.,  4.],
        [ 4.,  4.]]), array([[ 16.,  16.],
        [ 16.,  16.]])]

## Setting a Default Value for an Argument
Let’s say you want to define a function that adds two numbers, except that if you only provide one number, the other input is assumed to be one. You can do it like this: